app = "binance-spot-proxy"
primary_region = "fra"

[build]

[env]
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 1
  processes = ["app"]

[experimental]
  auto_rollback = true
